#version: '3'
services:
    reg:
        image: httpd:2.4
        ports:
            - '${REG_PORT:-80}:80'
        volumes:
            - '../apps/reg/dist:/var/www/html'
        networks:
            - evf
        depends_on:
            - api
            - mysql

    api:
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
        volumes:
            - '../api:/var/www/html'
        networks:
            - evf
        depends_on:
            - mysql

    wp:
        build:
            context: ./api
            dockerfile: Dockerfile
        volumes:
            - '../wordpress:/var/www/html/public'
        ports:
            - '${WP_PORT:-9080}:80'
        networks:
            - evf
        depends_on:
            - mysql

    mysql:
        image: 'mysql/mysql-server:8.0'
        command: mysqld --general-log=1 --general-log-file=/var/lib/mysql/general-log.log
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'local-mysql:/var/lib/mysql'
            - '../scripts/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - evf
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    mailpit:
        image: 'axllent/mailpit:latest'
        ports:
            - '${FORWARD_MAILPIT_PORT:-1025}:1025'
            - '${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025'
        networks:
            - evf

networks:
    evf:
        driver: bridge

volumes:
    local-mysql:
        driver: local
