#!/bin/bash

WD=$1
HOME=`pwd`
ARCHIVE="$HOME/$WD.zip"
VERSION=`php --version | grep '^PHP' | sed 's/PHP \([0-9]*\.[0-9]*\).*/\1/'`

if [[ ! "x$VERSION" = "x8.1" ]]
then
    echo "Expecting PHP version 8.1, received $VERSION"
    exit 1
fi

if [[ ! -e $ARCHIVE ]]
then
    echo "No upload detected, bailing"
    exit 1
fi

echo "Creating release directory"
mkdir -p $HOME/releases/$WD
echo "Unpacking release"
cd releases/$WD
unzip -q $ARCHIVE

if [[ -e "registration.zip" ]]
then
    echo "Unzipping registration application"
    mkdir registration
    cd registration
    unzip -q ../registration.zip
    cd ..
    rm registration.zip
else
    echo "ERROR: NO REGISTRATION APPLICATION"
    exit 1
fi

if [[ -e "API.zip" ]]
then
    echo "Unzipping API application"
    unzip -q API.zip
    rm API.zip

    if  [[ ! -e "api/.env" ]]
    then
        echo "ERROR: missing .env file"
        exit 1
    fi
else
    echo "ERROR: NO API APPLICATION"
    exit 1
fi

cd api

echo "Adjusting file permissions"
find ./ -type f -exec chmod 644 {} \;

echo "Adjusting directory permissions"
find ./ -type d -exec chmod 755 {} \;

#echo "Setting sticky bit"
#chmod 2777 bootstrap/cache

echo "Handling storage"
if [[ -e "storage" ]]
then
    rm -rf storage
fi
ln -sf $HOME/api_storage storage

echo "Migrating database"
cd $HOME/releases/$WD/api
php ./artisan migrate --force

# clear cache first, then restart the queue
# the queue-restart signal is stored on the cache
echo "Clearing caches"
php ./artisan cache:clear

echo "Restarting queue"
php artisan queue:restart

echo "Testing mail setup"
php artisan evf:report

echo "Switching releases"
cd $HOME/register.veteransfencing.eu
rm index.html assets
ln -sf $HOME/releases/$WD/registration/index.html .
ln -sf $HOME/releases/$WD/registration/assets .

cd $HOME/api.veteransfencing.eu
rm index.php
ln -sf $HOME/releases/$WD/api/public/index.php .
ln -sf $HOME/releases/$WD/api/public/.htaccess .

echo "Switching link to latest release"
mkdir -p $HOME/releases/last
cd $HOME/releases/last
rm -f api registration
ln -sf $HOME/releases/$WD/registration registration
ln -sf $HOME/releases/$WD/api api

echo "Cleanup"
rm $ARCHIVE $HOME/provision
